#ifndef CONSTANTES_H_INCLUDED
#define CONSTANTES_H_INCLUDED
#define TODO_OK 0
#define ARCHIVO_NO_ENCONTRADO 10
#define SIN_PARAMETROS 15
#define NO_SE_PUEDE_CREAR_ARCHIVO 20



#endif // CONSTANTES_H_INCLUDED
